### PR TITLE
separating the routes

### PR DESCRIPTION
**Pull request by Augasty**
Separated the routing in a different file as per our yesterday's discussion. 

ও দাদা, মার্জ করে দাও।

### CODE REVIEW

**Comment by Utshab500** [comment]
@Anupamdatta10 Please review the PR. You would have better insight than me here 😀

**Review by Utshab500 — COMMENTED** [review]
@Anupamdatta10  Please review the PR. You would have better insight than me here 😀

**Review by Anupamdatta10 — APPROVED** [review]
good to go

**Comment by Anupamdatta10** [comment]
good to go

**Pull request merged**
